"""Eviction Defense Engine - Generated by Seed"""
from typing import Dict, List

def analyze_eviction_notice(notice_text: str, jurisdiction: str) -> Dict:
    """Analyze eviction notice for defenses."""
    defenses = []
    
    # Check notice period
    if 'three day' in notice_text.lower() or '3 day' in notice_text.lower():
        defenses.append({
            'type': 'procedural',
            'defense': 'Insufficient notice period',
            'strength': 'high' if jurisdiction == 'CA' else 'medium'
        })
    
    # Check rent control
    if jurisdiction in ['SF', 'Oakland', 'LA']:
        defenses.append({
            'type': 'substantive',
            'defense': 'Rent control violation',
            'strength': 'high'
        })
    
    return {
        'defenses': defenses,
        'next_steps': [
            'File answer within 5 days',
            'Request discovery',
            'Gather rent payment evidence'
        ],
        'urgency': 'high'
    }

def generate_answer(case_info: Dict) -> str:
    """Generate answer to eviction complaint."""
    return f"""ANSWER TO UNLAWFUL DETAINER COMPLAINT

Case No: {case_info.get('case_number', '[CASE NUMBER]')}

COMES NOW the Defendant and states:

1. Defendant denies each allegation in Plaintiff's Complaint.
2. Defendant asserts the following affirmative defenses:
   - Failure to provide proper notice
   - Rent control violation
   - Retaliation for habitability complaints

WHEREFORE, Defendant requests judgment dismissing this action.

Dated: [DATE]
"""
