"""Motion Writer Engine - Generated by Seed"""

def generate_motion(motion_type: str, case_info: dict) -> str:
    """Generate court motion."""
    templates = {
        'continuance': _motion_continuance,
        'discovery': _motion_discovery,
        'summary_judgment': _motion_summary_judgment
    }
    
    generator = templates.get(motion_type, _motion_generic)
    return generator(case_info)

def _motion_continuance(info: dict) -> str:
    return f"""NOTICE OF MOTION FOR CONTINUANCE

Case No: {info['case_number']}

TO ALL PARTIES:
PLEASE TAKE NOTICE that on {info['hearing_date']}, Defendant will move for a continuance of trial.

This motion is made on grounds that additional time is needed to:
1. Complete discovery
2. Retain expert witnesses
3. Prepare defense

DATED: [DATE]
"""

def _motion_discovery(info: dict) -> str:
    return "MOTION TO COMPEL DISCOVERY..."

def _motion_summary_judgment(info: dict) -> str:
    return "MOTION FOR SUMMARY JUDGMENT..."

def _motion_generic(info: dict) -> str:
    return "MOTION [TYPE]..."
