"""Rent Calculator Engine - Generated by Seed"""
from typing import Dict

def calculate_rent_increase_legality(
    old_rent: float,
    new_rent: float,
    jurisdiction: str,
    year: int
) -> Dict:
    """Check if rent increase is legal."""
    increase_pct = ((new_rent - old_rent) / old_rent) * 100
    
    # Jurisdiction limits
    limits = {
        'CA': 10.0,  # AB 1482
        'SF': 7.0,
        'Oakland': 'CPI + 5%'
    }
    
    limit = limits.get(jurisdiction, float('inf'))
    is_legal = increase_pct <= limit if isinstance(limit, float) else True
    
    return {
        'old_rent': old_rent,
        'new_rent': new_rent,
        'increase_amount': new_rent - old_rent,
        'increase_percent': round(increase_pct, 2),
        'legal_limit': limit,
        'is_legal': is_legal,
        'recommendation': 'Dispute increase' if not is_legal else 'Increase is within limits'
    }
