name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m venv .venv
        . .venv/bin/activate
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        . .venv/bin/activate
        python -m pytest -q

    - name: Build Docker image (tests already ran)
      run: |
        docker build -t semptifygui:ci .
