name: Generate Markdown from HTML Docs

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**/*.html'
  schedule:
    - cron: '17 4 * * 1' # weekly Monday 04:17 UTC

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv (for uvx)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Convert HTML docs to Markdown
        id: convert
        run: |
          set -euo pipefail
          HTML_FILES=$(find docs -type f -name '*.html' || true)
          if [ -z "$HTML_FILES" ]; then
            echo "No HTML files found under docs/"; exit 0; fi
          for f in $HTML_FILES; do
            base="${f%.html}.md"
            echo "Converting $f -> $base"
            ~/.local/bin/uvx markitdown "$f" > "$base.tmp"
            # Only replace if different to avoid noisy commits
            if [ -f "$base" ] && diff -q "$base" "$base.tmp" >/dev/null 2>&1; then
              echo "No changes for $base"
              rm "$base.tmp"
            else
              mv "$base.tmp" "$base"
              echo "Updated $base"
            fi
          done
      
      - name: Commit updated Markdown (if any)
        run: |
          set -e
          if git diff --quiet; then
            echo "No doc changes to commit."; exit 0; fi
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
            
          git add docs/**/*.md
          git commit -m "docs(markdown): automated conversion from HTML via markitdown"
          git push
      
      - name: Upload Markdown artifacts
        uses: actions/upload-artifact@v4
        with:
          name: markdown-docs-${{ github.run_id }}
          path: |
            docs/**/*.md