name: Render Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4 * * *'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install robot deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
      - name: Determine BASE_URL
        id: base
        run: |
          if [ -z "${{ secrets.RENDER_BASE_URL }}" ]; then echo "No RENDER_BASE_URL; skipping"; echo "skip=true" >> $GITHUB_OUTPUT; exit 0; fi
          echo "url=${{ secrets.RENDER_BASE_URL }}" >> $GITHUB_OUTPUT
      - name: Run Robot smoke
        if: steps.base.outputs.skip != 'true'
        run: |
          robot -v BASE_URL:${{ steps.base.outputs.url }} robot/smoke.robot
      - name: Summary
        if: always()
        run: |
          echo "Render smoke result: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY